# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9993afb05a4a05735d1a575acf5c41acad392360a9678686ba2a4d2a60a5ccb01b0930816c4e63a493b2c0cbdadec9275082b57fd6978e961e2fa20494d6fd1e

test:
  secret_key_base: faaa27b9aedf5aa391bc27c14db55ce9a849e1e3d760db7785fa38f994b2da79fd7e74fd010df4f98faa64c2870ef6d9ae30430ad1632475af032b5d02c771ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
